language: cpp

notifications:
   email: false

matrix:
   include:
      - env: PLATFORM=linux RELEASE=true
        os: linux
        dist: trusty
        sudo: required

      - env: PLATFORM=linux RELEASE=false QMAKESPEC=linux-clang
        os: linux
        dist: trusty
        sudo: required

      - env: PLATFORM=mac RELEASE=true
        os: osx

      - env: PLATFORM=windows RELEASE=true BITS=32
        os: linux
        dist: trusty
        sudo: required

      - env: PLATFORM=windows RELEASE=true BITS=64
        os: linux
        dist: trusty
        sudo: required
   allow_failures:
      - env: PLATFORM=windows RELEASE=true BITS=32
      - env: PLATFORM=windows RELEASE=true BITS=64

before_install:
   - source ./build/${PLATFORM}/requirement.sh

install:
   - qmake -config release
   - make

script:
   - source ./build/${PLATFORM}/test.sh

before_deploy:
   - source ./build/${PLATFORM}/package.sh

deploy:
   provider: releases
   api_key:
      secure: arYILOeUtsJ0lpMF2hZGHSnlC/ACvjwvpqXLCRWLmwbFEnTUR4RLZ0ZuEACgEVVCrQEBe0F187w2pMq9cRjsX3EF0t+CVClMZqLAkYjE9fUezDErMl8WuYqYVooI/QZ62hbo11bmFcl7B88t/owVc0HxMg66AtbA/XV8AbMDuOOsLS0I4NylZ4jVNarcuCbTm8DZfOhvPbAHWLMql2Bwri6t2Xw3GqvFOfANZiiyC7WvjNKSEXaN8wi3kFJnjpTNVaRg7AuVcn+DcpJfSmgNnNSiNRCHUHJCmxegkAbFcCQ8SV+ij6lx8Vtt7+87HoRbNLyCbXrVVw95aCnuLBrMKiT5dgTXpxCtruzi1lDBRtHq7A6NQJL5FvYnx/wb2v8XcndaZWYivFrgRjTiwnO0c/Lh5omf1MB4GjY3a4SdPdLIUir9N7jhvRZ3HUkNyGKNtKn663mUnVn4nR5rKZdwyOiHGkftBoIfiSt0ZhXEPICn1rPvDh7LirPRbGLBNbT2EYyRyFIc/udbkOGOxR06XTiaack5Gn6qDCSHWHXyxsJAAztUTc/Cq8e+YCEfVZLC7kbCnAO0793gnxBJLZRrVgOU1KKhbOiFyv3MIdAiFSLix3qLJ1o/sJjwzJot8Fv+62vY7JqtCT+DjwHZMGr5aA7bpM4CrOBY+OLqBpItK/E=
   file: "$(ls pdftalk-${PLATFORM}*)"
   skip_cleanup: true
   on:
      repo: lereldarion/pdftalk
      tags: true
      condition: $RELEASE = true
