name: ci
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-qmake libpoppler-qt5-dev
      - run: qmake
      - run: make
      - name: Test run (usage)
        run: ./pdftalk --platform offscreen -h
      # Release stuff
      - run: mv pdftalk pdftalk-x86_64-ubuntu
      - name: Upload release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "pdftalk-x86_64-ubuntu"
          token: ${{ secrets.GITHUB_TOKEN }}
